USE LIBRARY_DB;

DELIMITER //

CREATE PROCEDURE GetBooksByAuthor(IN authorName VARCHAR(150))
BEGIN
    SELECT B.TITLE, B.PUB_YEAR, B.GENRE
    FROM BOOKS B
    JOIN BOOKAUTHORS BA ON B.BOOK_ID = BA.BOOK_ID
    JOIN AUTHORS A ON BA.AUTH_ID = A.AUTH_ID
    WHERE A.NAME = authorName;
END //

CREATE FUNCTION GetMemberLoanCount(memberId INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE loanCount INT;
    SELECT COUNT(*) INTO loanCount
    FROM LOANS
    WHERE MEMBER_ID = memberId;
    RETURN loanCount;
END //

DELIMITER ;

CALL GetBooksByAuthor('GEORGE ORWELL');
SELECT GetMemberLoanCount(2) AS LoanCount;
