
USE LIBRARY_DB;

SELECT B.TITLE, A.NAME AS AUTHOR
FROM BOOKS B
INNER JOIN BOOKAUTHORS BA ON B.BOOK_ID = BA.BOOK_ID
INNER JOIN AUTHORS A ON BA.AUTH_ID = A.AUTH_ID;

SELECT B.TITLE, A.NAME AS AUTHOR
FROM BOOKS B
LEFT JOIN BOOKAUTHORS BA ON B.BOOK_ID = BA.BOOK_ID
LEFT JOIN AUTHORS A ON BA.AUTH_ID = A.AUTH_ID;

SELECT A.NAME AS AUTHOR, B.TITLE
FROM AUTHORS A
LEFT JOIN BOOKAUTHORS BA ON A.AUTH_ID = BA.AUTH_ID
LEFT JOIN BOOKS B ON BA.BOOK_ID = B.BOOK_ID;

SELECT B.TITLE, A.NAME AS AUTHOR
FROM BOOKS B
LEFT JOIN BOOKAUTHORS BA ON B.BOOK_ID = BA.BOOK_ID
LEFT JOIN AUTHORS A ON BA.AUTH_ID = A.AUTH_ID
UNION
SELECT B.TITLE, A.NAME AS AUTHOR
FROM AUTHORS A
LEFT JOIN BOOKAUTHORS BA ON A.AUTH_ID = BA.AUTH_ID
LEFT JOIN BOOKS B ON BA.BOOK_ID = B.BOOK_ID;

SELECT A.NAME AS AUTHOR, B.TITLE
FROM AUTHORS A
CROSS JOIN BOOKS B;

SELECT M.NAME AS MEMBER, B.TITLE, L.LOAN_DATE
FROM LOANS L
JOIN MEMBERS M ON L.MEMBER_ID = M.MEMBER_ID
JOIN BOOKS B ON L.BOOK_ID = B.BOOK_ID
WHERE L.LOAN_DATE >= '2023-06-01';