
USE LIBRARY_DB;


SELECT 
    LOAN_ID,
    (SELECT NAME FROM MEMBERS WHERE MEMBERS.MEMBER_ID = LOANS.MEMBER_ID) AS MEMBER_NAME,
    (SELECT TITLE FROM BOOKS WHERE BOOKS.BOOK_ID = LOANS.BOOK_ID) AS BOOK_TITLE,
    LOAN_DATE,
    RETURN_DATE
FROM LOANS;



SELECT * 
FROM BOOKS 
WHERE BOOK_ID IN (
    SELECT BOOK_ID 
    FROM BOOKAUTHORS 
    WHERE AUTH_ID = (
        SELECT AUTH_ID 
        FROM AUTHORS 
        WHERE NAME = 'GEORGE ORWELL'
    )
);



SELECT A.NAME, COUNT(BA.BOOK_ID) AS BOOK_COUNT
FROM (
    SELECT * 
    FROM BOOKAUTHORS
) AS BA
JOIN AUTHORS A ON A.AUTH_ID = BA.AUTH_ID
GROUP BY A.NAME;
