CREATE DATABASE LIBRARY_DB;

USE LIBRARY_DB;

CREATE TABLE AUTHORS (
  AUTH_ID INT PRIMARY KEY,
  NAME VARCHAR(150) NOT NULL
);


CREATE TABLE BOOKS (
  BOOK_ID INT PRIMARY KEY,
  TITLE VARCHAR(150) NOT NULL,
  PUB_YEAR INT,
  GENRE VARCHAR(150)
);


CREATE TABLE MEMBERS (
MEMBER_ID INT PRIMARY KEY,
NAME VARCHAR(150) NOT NULL,
JOIN_DATE DATE NOT NULL
);


CREATE TABLE LOANS (
LOAN_ID INT PRIMARY KEY,
MEMBER_ID INT NOT NULL,
BOOK_ID INT NOT NULL,
LOAN_DATE DATE NOT NULL,
RETURN_DATE DATE,
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,

FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);


CREATE TABLE BOOKAUTHORS (
BOOK_ID INT NOT NULL,
AUTH_ID INT NOT NULL,

PRIMARY KEY (BOOK_ID, AUTH_ID),
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
ON DELETE CASCADE
ON UPDATE CASCADE,

FOREIGN KEY (AUTH_ID) REFERENCES AUTHORS(AUTH_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
);







