USE LIBRARY_DB;

SELECT * FROM BOOKS;

SELECT TITLE, PUB_YEAR 
FROM BOOKS;

SELECT * FROM BOOKS
WHERE GENRE = 'FANTASY';

SELECT * FROM BOOKS
WHERE GENRE = 'FANTASY' AND PUB_YEAR > 1950;

SELECT * FROM BOOKS
WHERE GENRE = 'FANTASY' OR GENRE = 'MYSTERY';

SELECT * FROM BOOKS
WHERE TITLE LIKE 'THE%';

SELECT * FROM AUTHORS
WHERE NAME LIKE '%GEORGE%';

SELECT * FROM BOOKS
WHERE PUB_YEAR BETWEEN 1930 AND 1950;

SELECT * FROM MEMBERS
WHERE JOIN_DATE BETWEEN '2023-01-01' AND '2023-02-28';

SELECT * FROM BOOKS
ORDER BY PUB_YEAR ASC;

SELECT * FROM MEMBERS
ORDER BY JOIN_DATE DESC;

SELECT TITLE, PUB_YEAR, GENRE FROM BOOKS
WHERE GENRE = 'FANTASY' AND PUB_YEAR > 1950
ORDER BY PUB_YEAR DESC;
