USE LIBRARY_DB;

SELECT GENRE, COUNT(*) AS NUM_BOOKS
FROM BOOKS
GROUP BY GENRE;

SELECT M.NAME AS MEMBER_NAME, COUNT(L.LOAN_ID) AS TOTAL_LOANS
FROM MEMBERS M
JOIN LOANS L ON M.MEMBER_ID = L.MEMBER_ID
GROUP BY M.MEMBER_ID;

SELECT GENRE, AVG(PUB_YEAR) AS AVG_PUB_YEAR
FROM BOOKS
GROUP BY GENRE;

SELECT A.NAME AS AUTHOR_NAME, COUNT(BA.BOOK_ID) AS BOOK_COUNT
FROM AUTHORS A
JOIN BOOKAUTHORS BA ON A.AUTH_ID = BA.AUTH_ID
GROUP BY A.AUTH_ID;

SELECT B.GENRE, COUNT(*) AS LOANS_COUNT
FROM LOANS L
JOIN BOOKS B ON L.BOOK_ID = B.BOOK_ID
GROUP BY B.GENRE;

SELECT M.NAME AS MEMBER_NAME, 
       COUNT(L.LOAN_ID) AS NUM_LOANS,
       SUM(JULIANDAY(L.RETURN_DATE) - JULIANDAY(L.LOAN_DATE)) AS TOTAL_DAYS_BORROWED,
       AVG(JULIANDAY(L.RETURN_DATE) - JULIANDAY(L.LOAN_DATE)) AS AVG_DAYS_BORROWED
FROM MEMBERS M
JOIN LOANS L ON M.MEMBER_ID = L.MEMBER_ID
GROUP BY M.MEMBER_ID;
